### PR TITLE
adding artichoke and parsley

### LINKED ISSUE #3: add artichoke and parsley

### PR DESCRIPTION
**Pull request by SwissalpS**

### CODE REVIEW

**Comment by OgelGames** [comment]
Looks good, but they should be added to the trader too 😉

**Comment by SwissalpS** [comment]
> Looks good, but they should be added to the trader too

good point.

**Comment by SwissalpS** [comment]
shouldn't artichoke be a bit rarer or at least more expensive than parsley?
Finding parsley in the wild is a lot easier than artichoke (I found, in new area, about three mint before I found first artichoke)

**Comment by OgelGames** [comment]
I guess it could be... Feel free to make another PR to change that (or any of the farming items, not much difference between most of them)

**Pull request merged**
